name: Publish gdcore-tools for new GDevelop version

on:
  repository_dispatch:
    types: [gdevelop-release]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - uses: actions/checkout@v4
        with:
          repository: 4ian/GDevelop
          path: GDevelop
          ref: refs/tags/${{ github.event.client_payload.release.tag_name }}
      - uses: actions/checkout@v4
        with:
          path: gdcore-tools

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          sudo apt-get install -y jq
          ./emsdk/emsdk install 3.1.21
          ./emsdk/emsdk activate 3.1.21
          cd gdcore-tools
          new_version="$(node -e "console.log($(jq '.version' package.json).split('-')[0])")-commit_${{ github.event.client_payload.release.target_commitish }}"
          jq ".version = $new_version" package.json

      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}